{
  "recipe": {
    "name": "Coopers Pale Ale",
    "version": 1,
    "type": "All Grain",
    "brewer": "Andrew Clark",
    "asst_brewer": "",
    "batch_size": 23.02,
    "boil_size": 37.1203164,
    "boil_time": 90,
    "efficiency": 68,
    "hops": [
      {
        "name": "Pride of Ringwood",
        "version": 1,
        "origin": "Australia",
        "alpha": 8.3,
        "amount": 0.0325766,
        "use": "Boil",
        "time": 60,
        "notes": "Use for: General purpose bittering hops for Australian beers\nAroma: Moderate citric aroma, clean bittering flavor\nSubstitutes: Cluster, Galena",
        "type": "Bittering",
        "form": "Pellet",
        "beta": 5.75,
        "hsi": 45,
        "display_amount": "1.15 oz",
        "inventory": "1.02 oz",
        "display_time": "60.0 min",
        "id": "64690112-c793-4033-a63b-42030868436c",
        "complete": false
      }
    ],
    "fermentables": [
      {
        "name": "Pale Malt, Ale (Barrett Burston)",
        "version": 1,
        "type": "Grain",
        "amount": 4.4117619,
        "yield": 80,
        "color": 2.0304569,
        "add_after_boil": false,
        "origin": "Australia",
        "supplier": "Barrett Burston",
        "notes": "Good pale 2-row base spring malting grade barley. Well-modified and kilned malt is required.",
        "coarse_fine_diff": 1.5,
        "moisture": 4.5,
        "diastatic_power": 230,
        "protein": 0,
        "max_in_batch": 100,
        "recommend_mash": true,
        "ibu_gal_per_lb": 0,
        "display_amount": "9 lbs 11.6 oz",
        "inventory": "8 lbs 4.3 oz",
        "potential": 1.0368,
        "display_color": "2.0 SRM",
        "extract_substitute": "Pale Liquid Extract",
        "id": "9fc07775-4441-412d-878c-52917e78c589",
        "complete": false
      },
      {
        "name": "Wheat Malt (Barrett Burston)",
        "version": 1,
        "type": "Grain",
        "amount": 0.235294,
        "yield": 81.1,
        "color": 1.2182741,
        "add_after_boil": false,
        "origin": "Australia",
        "supplier": "Barrett Burston",
        "notes": "Wheat base malt suitable for all wheat styles.",
        "coarse_fine_diff": 1.5,
        "moisture": 5,
        "diastatic_power": 95,
        "protein": 0,
        "max_in_batch": 75,
        "recommend_mash": true,
        "ibu_gal_per_lb": 0,
        "display_amount": "8.3 oz",
        "inventory": "7.1 oz",
        "potential": 1.037306,
        "display_color": "1.2 SRM",
        "extract_substitute": "Pale Liquid Extract",
        "id": "335cc51b-4c54-4b21-9c47-2019dd0e5d1d",
        "complete": false
      },
      {
        "name": "Crystal Dark Bairds",
        "version": 1,
        "type": "Grain",
        "amount": 0.0470588,
        "yield": 74.4,
        "color": 121.8274112,
        "add_after_boil": false,
        "origin": "Australia",
        "supplier": "Bairds",
        "notes": "Medium-dark crystal malt. Used for color and flavor. Use 5% to 10% for improved colour aroma. Subtle crystal sweetness.",
        "coarse_fine_diff": 1.5,
        "moisture": 5.2,
        "diastatic_power": 0,
        "protein": 0,
        "max_in_batch": 10,
        "recommend_mash": false,
        "ibu_gal_per_lb": 0,
        "display_amount": "1.7 oz",
        "inventory": "1.4 oz",
        "potential": 1.034224,
        "display_color": "121.8 SRM",
        "extract_substitute": "",
        "id": "c390ed11-2c92-4ea6-95fa-5f7ae9d23edf",
        "complete": false
      }
    ],
    "miscs": [
      {
        "name": "Gypsum (Calcium Sulfate)",
        "version": 1,
        "type": "Water Agent",
        "use": "Mash",
        "amount": 0.004,
        "time": 60,
        "amount_is_weight": true,
        "use_for": "Water Agent",
        "notes": "Reduces PH of water for mashing and sparging. Alters water profile -- used to harden soft water. Use the BeerSmith Water Profile tool to determine amount to add.",
        "display_amount": "4.00 g",
        "inventory": "192.00 g",
        "display_time": "60.0 mins",
        "batch_size": "5.00 gal",
        "id": "4eac4782-3f3c-48d0-aa28-b2b576345771",
        "complete": false
      },
      {
        "name": "Calcium Chloride",
        "version": 1,
        "type": "Water Agent",
        "use": "Mash",
        "amount": 0.002,
        "time": 60,
        "amount_is_weight": true,
        "use_for": "Water Agent",
        "notes": "Alters water profile and pH of mash. Use the BeerSmith Water Profile tool to determine amount to add.",
        "display_amount": "2.00 g",
        "inventory": "194.50 g",
        "display_time": "60.0 mins",
        "batch_size": "5.00 gal",
        "id": "b4537456-d4d7-42df-8cdf-84db4dd1ad04",
        "complete": false
      },
      {
        "name": "Epsom Salt (MgSO4)",
        "version": 1,
        "type": "Water Agent",
        "use": "Mash",
        "amount": 0.002,
        "time": 60,
        "amount_is_weight": true,
        "use_for": "Water Agent",
        "notes": "Water agent used to modify water profile. Use the BeerSmith Water Profile tool to determine amount to add.",
        "display_amount": "2.00 g",
        "inventory": "196.00 g",
        "display_time": "60.0 mins",
        "batch_size": "5.00 gal",
        "id": "06d53d84-5974-4e09-bbb5-4cec0997e3ae",
        "complete": false
      },
      {
        "name": "Whirlfloc Tablet",
        "version": 1,
        "type": "Fining",
        "use": "Boil",
        "amount": 1,
        "time": 10,
        "amount_is_weight": false,
        "use_for": "Clarity",
        "notes": "Aids in clearing yeast and chill haze. Easy to use tablet form.",
        "display_amount": "1.00 Items",
        "inventory": "0.00 Items",
        "display_time": "10.0 mins",
        "batch_size": "5.28 gal",
        "id": "9aa8a0db-2ac9-4369-8852-b54379a0e7f5",
        "complete": false
      },
      {
        "name": "Yeast Nutrient",
        "version": 1,
        "type": "Other",
        "use": "Boil",
        "amount": 0.004929,
        "time": 10,
        "amount_is_weight": false,
        "use_for": "Fermentation",
        "notes": "Gives yeast nutrients for healthy fermentation. Not needed for most beers, but good for those with a high percentage of adjuncts. Add before yeast.",
        "display_amount": "1.00 tsp",
        "inventory": "180.00 tsp",
        "display_time": "10.0 mins",
        "batch_size": "5.00 gal",
        "id": "def57285-8957-4bf1-9fa7-64d1663cd306",
        "complete": false
      }
    ],
    "yeasts": [
      {
        "name": "Coopers pale Ale Cultured",
        "version": 1,
        "type": "Ale",
        "form": "Liquid",
        "amount": 1,
        "amount_is_weight": false,
        "laboratory": "",
        "product_id": "CPA",
        "min_temperature": 18.3,
        "max_temperature": 22.8,
        "flocculation": "Medium",
        "attenuation": 75,
        "notes": "",
        "best_for": "",
        "max_reuse": 5,
        "times_cultured": 0,
        "add_to_secondary": false,
        "display_amount": "1000.00 ml",
        "disp_min_temp": "64.9 F",
        "disp_max_temp": "73.0 F",
        "inventory": "1.0 pkg",
        "culture_date": "22 Jan 2009",
        "id": "36553997-f4e8-4156-87eb-8113fa568125",
        "complete": false
      }
    ],
    "style": {
      "name": "Australian Pale Ale",
      "version": 1,
      "category": "Australian Pale Ale",
      "category_number": 8,
      "style_letter": "D",
      "style_guide": "BJCP 2004",
      "type": "Ale",
      "og_min": 1.035,
      "og_max": 1.048,
      "fg_min": 1.004,
      "fg_max": 1.006,
      "ibu_min": 25,
      "ibu_max": 40,
      "color_min": 3,
      "color_max": 7,
      "carb_min": 2.2,
      "carb_max": 2.8,
      "abv_max": 6,
      "abv_min": 4.2,
      "notes": "",
      "profile": "",
      "ingredients": "",
      "examples": "",
      "display_og_min": "1.035 SG",
      "display_og_max": "1.048 SG",
      "display_fg_min": "1.004 SG",
      "display_fg_max": "1.006 SG",
      "display_color_min": "3.0 SRM",
      "display_color_max": "7.0 SRM",
      "og_range": "1.035-1.048 SG",
      "fg_range": "1.004-1.006 SG",
      "ibu_range": "25.0-40.0 IBUs",
      "carb_range": "2.20-2.80 Vols",
      "color_range": "3.0-7.0 SRM",
      "abv_range": "4.20-6.00 %"
    },
    "equipment": {
      "name": "Pot (18.5 Gal/70 L) and Cooler (9.5 Gal/40 L) - All Grain",
      "version": 1,
      "boil_size": 37.1203164,
      "batch_size": 23.02,
      "tun_volume": 37.85,
      "tun_weight": 4.082328,
      "tun_specific_heat": 0.3,
      "top_up_water": 0,
      "trub_chiller_loss": 2.84,
      "evap_rate": 18.2879483,
      "boil_time": 90,
      "calc_boil_volume": true,
      "lauter_deadspace": 3.03,
      "top_up_kettle": 0,
      "hop_utilization": 100,
      "cooling_loss_pct": 4,
      "notes": "Based on a 18.5 Gal/70 L pot with a diameter of 18 inches/45 cm and a 9.5 Gal/40 L cooler. The above assumes loose pellet hops and only clear, chilled wort transferred from the kettle using no trub management techniques. Experienced brewers should adjust 'Loss to Trub and Chiller' and 'Brewhouse Efficiency' accordingly to suit their trub management techniques.",
      "display_boil_size": "9.81 gal",
      "display_batch_size": "6.08 gal",
      "display_tun_volume": "10.00 gal",
      "display_tun_weight": "9 lbs",
      "display_top_up_water": "0.00 gal",
      "display_trub_chiller_loss": "0.75 gal",
      "display_lauter_deadspace": "0.80 gal",
      "display_top_up_kettle": "0.00 gal"
    },
    "mash": {
      "name": "Pilsner Mash",
      "version": 1,
      "grain_temp": 22.2,
      "tun_temp": 22,
      "sparge_temp": 78,
      "ph": 5.4,
      "tun_weight": 144,
      "tun_specific_heat": 0.3,
      "equip_adjust": true,
      "notes": "",
      "display_grain_temp": "72.0 F",
      "display_tun_temp": "71.6 F",
      "display_sparge_temp": "172.4 F",
      "display_tun_weight": "9 lbs"
    },
    "notes": "Great Clone",
    "taste_notes": "This is as close as I can get, pretty much identical to CPA, taste and color are spot on.\nSpecs for the beer are direct from coopers.",
    "taste_rating": 48,
    "og": 1.043,
    "fg": 1.01,
    "carbonation": 2.4,
    "fermentation_stages": 2,
    "primary_age": 7,
    "primary_temp": 18,
    "secondary_age": 2,
    "secondary_temp": 2,
    "tertiary_age": 0,
    "age": 14,
    "age_temp": 6,
    "carbonation_used": "Keg with 13.72 PSI",
    "forced_carbonation": false,
    "priming_sugar_name": "Forced Carbonation",
    "priming_sugar_equiv": 1,
    "keg_priming_factor": 0.5,
    "carbonation_temp": 7.2222222,
    "display_carb_temp": "45.0 F",
    "date": "14 May 2011",
    "est_og": "1.043 SG",
    "est_fg": "1.006 SG",
    "est_color": "4.4 SRM",
    "ibu": "31.7 IBUs",
    "ibu_method": "Tinseth",
    "est_abv": "4.7 %",
    "abv": "4.3 %",
    "actual_efficiency": "68.7 %",
    "calories": "141.5 kcal/12oz",
    "display_batch_size": "6.08 gal",
    "display_boil_size": "9.81 gal",
    "display_og": "1.043 SG",
    "display_fg": "1.010 SG",
    "display_primary_temp": "64.4 F",
    "display_secondary_temp": "35.6 F",
    "display_tertiary_temp": "68.0 F",
    "display_age_temp": "42.8 F",
    "mash_steps": [
      {
        "name": "Mash In",
        "version": 1,
        "type": "Infusion",
        "infuse_amount": 18.7764211,
        "step_time": 5,
        "step_temp": 35,
        "ramp_time": 2,
        "end_temp": 35,
        "description": "Add 23.04 qt of water at 98.0 F",
        "water_grain_ratio": "1.917 qt/lb",
        "decoction_amt": "0.00 qt",
        "infuse_temp": "98.0 F",
        "display_step_temp": "95.0 F",
        "display_infuse_amt": "23.04 qt",
        "id": "05b45621-a062-47eb-8604-b9d9b6deb708",
        "complete": false
      },
      {
        "name": "Protien Rest",
        "version": 1,
        "type": "Temperature",
        "infuse_amount": 0,
        "step_time": 15,
        "step_temp": 52,
        "ramp_time": 10,
        "end_temp": 52,
        "description": "Heat to 125.6 F over 10 min",
        "water_grain_ratio": "2.227 qt/lb",
        "decoction_amt": "0.00 qt",
        "infuse_temp": "170.0 F",
        "display_step_temp": "125.6 F",
        "display_infuse_amt": "0.00 qt",
        "id": "6d98d3bc-6ec3-4b8c-b651-690a3bcfc4a3",
        "complete": false
      },
      {
        "name": "Sacch Rest",
        "version": 1,
        "type": "Temperature",
        "infuse_amount": 0,
        "step_time": 60,
        "step_temp": 63,
        "ramp_time": 10,
        "end_temp": 63,
        "description": "Heat to 145.4 F over 10 min",
        "water_grain_ratio": "2.227 qt/lb",
        "decoction_amt": "0.00 qt",
        "infuse_temp": "170.0 F",
        "display_step_temp": "145.4 F",
        "display_infuse_amt": "0.00 qt",
        "id": "1a3904ea-8cb9-4b2c-a551-89b071afa393",
        "complete": false
      },
      {
        "name": "Mash Out",
        "version": 1,
        "type": "Temperature",
        "infuse_amount": 0,
        "step_time": 10,
        "step_temp": 78,
        "ramp_time": 10,
        "end_temp": 78,
        "description": "Heat to 172.4 F over 10 min",
        "water_grain_ratio": "2.227 qt/lb",
        "decoction_amt": "0.00 qt",
        "infuse_temp": "170.0 F",
        "display_step_temp": "172.4 F",
        "display_infuse_amt": "0.00 qt",
        "id": "2d1e003c-59cf-4c7f-a31e-ebee8fc6b77d",
        "complete": false
      }
    ],
    "steps": [
      {
        "id": "9cae17d0-0730-4df8-87f0-890f6fa85750",
        "title": "Strike Water",
        "subheader": null,
        "content": "Add the following ingredients to the Hot Liquor Tank:",
        "todos": [
          {
            "step": "9.81 gal water",
            "complete": false,
            "id": "96bcc0a1-79a2-4f34-8186-1cbae1ade046"
          },
          {
            "step": "4.00 g Gypsum (Calcium Sulfate)",
            "complete": false,
            "id": "d9401432-752b-46bf-8950-114c551be65c"
          },
          {
            "step": "2.00 g Calcium Chloride",
            "complete": false,
            "id": "2c4dc258-16cf-4499-8c82-ae974290c06e"
          },
          {
            "step": "2.00 g Epsom Salt (MgSO4)",
            "complete": false,
            "id": "a819a090-0a59-4bc4-ad07-7928cc822635"
          }
        ],
        "objects": [
          {
            "name": "Gypsum (Calcium Sulfate)",
            "version": 1,
            "type": "Water Agent",
            "use": "Mash",
            "amount": 0.004,
            "time": 60,
            "amount_is_weight": true,
            "use_for": "Water Agent",
            "notes": "Reduces PH of water for mashing and sparging. Alters water profile -- used to harden soft water. Use the BeerSmith Water Profile tool to determine amount to add.",
            "display_amount": "4.00 g",
            "inventory": "192.00 g",
            "display_time": "60.0 mins",
            "batch_size": "5.00 gal",
            "id": "4eac4782-3f3c-48d0-aa28-b2b576345771",
            "complete": false
          },
          {
            "name": "Calcium Chloride",
            "version": 1,
            "type": "Water Agent",
            "use": "Mash",
            "amount": 0.002,
            "time": 60,
            "amount_is_weight": true,
            "use_for": "Water Agent",
            "notes": "Alters water profile and pH of mash. Use the BeerSmith Water Profile tool to determine amount to add.",
            "display_amount": "2.00 g",
            "inventory": "194.50 g",
            "display_time": "60.0 mins",
            "batch_size": "5.00 gal",
            "id": "b4537456-d4d7-42df-8cdf-84db4dd1ad04",
            "complete": false
          },
          {
            "name": "Epsom Salt (MgSO4)",
            "version": 1,
            "type": "Water Agent",
            "use": "Mash",
            "amount": 0.002,
            "time": 60,
            "amount_is_weight": true,
            "use_for": "Water Agent",
            "notes": "Water agent used to modify water profile. Use the BeerSmith Water Profile tool to determine amount to add.",
            "display_amount": "2.00 g",
            "inventory": "196.00 g",
            "display_time": "60.0 mins",
            "batch_size": "5.00 gal",
            "id": "06d53d84-5974-4e09-bbb5-4cec0997e3ae",
            "complete": false
          }
        ],
        "complete": false,
        "type": "PREPARE_STRIKE_WATER"
      },
      {
        "id": "c7fc08ec-f4de-4406-8e1d-9c8a5824ed8f",
        "title": "Prepare for Heating Strike Water",
        "content": "Put valves in recirculating position:",
        "todos": [
          {
            "step": "Open HLT outlet",
            "complete": false,
            "id": "85311754-74e8-4cec-a56c-6a1a2edd4513"
          },
          {
            "step": "Open pump outlet",
            "complete": false,
            "id": "7a6ded0a-10b1-459f-8c1d-e3a816f4fbf0"
          },
          {
            "step": "Close top Mash Tun inlet so water flows back to HLT",
            "complete": false,
            "id": "7c6a7094-d7fc-45d5-98f6-d97e5a6ff6bb"
          }
        ],
        "complete": false,
        "type": "PREPARE_FOR_HTL_HEAT"
      },
      {
        "id": "554785ba-ec53-43bf-9aa2-351bad2d4347",
        "title": "Heat Strike Water",
        "content": "Heating strike water to 98.0 F",
        "objects": [
          {
            "name": "Mash In",
            "version": 1,
            "type": "Infusion",
            "infuse_amount": 18.7764211,
            "step_time": 5,
            "step_temp": 35,
            "ramp_time": 2,
            "end_temp": 35,
            "description": "Add 23.04 qt of water at 98.0 F",
            "water_grain_ratio": "1.917 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "98.0 F",
            "display_step_temp": "95.0 F",
            "display_infuse_amt": "23.04 qt",
            "id": "05b45621-a062-47eb-8604-b9d9b6deb708",
            "complete": false
          }
        ],
        "setpoint": 98,
        "complete": false,
        "type": "HEATING"
      },
      {
        "id": "85614392-3d41-45c4-9c84-5495fb4a5338",
        "title": "Fill Mash Tun",
        "content": "Fill mash tun with 23.04 qt water",
        "todos": [
          {
            "step": "Open top Mash Tun inlet so water flows into the Mash Tun",
            "complete": false,
            "id": "3a5af102-3306-4fe8-b9c1-d06738e52e9a"
          },
          {
            "step": "Add 23.04 qt water",
            "complete": false,
            "id": "c861e7cc-01ed-4277-8aa1-7137e5291daa"
          }
        ],
        "complete": false,
        "type": "ADD_WATER_TO_MASH_TUN"
      },
      {
        "id": "239c81e6-716b-4821-9a32-2edbf1e5b71f",
        "title": "Prepare for Mash Tun Recirculation",
        "content": "Put valves in recirculating position:",
        "todos": [
          {
            "step": "Close HLT outlet",
            "complete": false,
            "id": "c7879953-f078-43fd-a3a6-f3ac10258abb"
          },
          {
            "step": "Open pump outlet",
            "complete": false,
            "id": "8da4fcaf-e7bc-49cf-ab1d-62bb08119f68"
          },
          {
            "step": "Open top Mash Tun inlet so water flows back to Mash Tun",
            "complete": false,
            "id": "0afba0ad-3d6b-41c7-b849-1320476ff171"
          },
          {
            "step": "Cap top HLT inlet",
            "complete": false,
            "id": "8de04d81-9cc8-4856-830c-b31459b18c2e"
          }
        ],
        "complete": false,
        "type": "PREPARE_FOR_MASH_RECIRC"
      },
      {
        "id": "731624d8-6351-4f5a-9fe3-1028cde7dc7a",
        "title": "Add Ingredients to Mash Tun",
        "content": "Add the following ingredients to the Mash Tun:",
        "todos": [
          {
            "step": "9 lbs 11.6 oz Pale Malt, Ale (Barrett Burston)",
            "complete": false,
            "id": "86d95478-2ed1-4864-a322-49e1160a56a5"
          },
          {
            "step": "8.3 oz Wheat Malt (Barrett Burston)",
            "complete": false,
            "id": "0f84d38c-5bf3-45a0-9819-bc4298058d8f"
          },
          {
            "step": "1.7 oz Crystal Dark Bairds",
            "complete": false,
            "id": "e675fe99-2796-4ec6-a3f3-601f67020ef1"
          },
          {
            "step": "4.00 g Gypsum (Calcium Sulfate)",
            "complete": false,
            "id": "b193a6c0-50fd-4aa9-98f6-10b3dbd8d10a"
          },
          {
            "step": "2.00 g Calcium Chloride",
            "complete": false,
            "id": "8122380e-fddb-413f-9975-14761077737f"
          },
          {
            "step": "2.00 g Epsom Salt (MgSO4)",
            "complete": false,
            "id": "ca278b8a-0ef9-45e2-bd06-48d286ebcad9"
          }
        ],
        "objects": [
          {
            "name": "Pale Malt, Ale (Barrett Burston)",
            "version": 1,
            "type": "Grain",
            "amount": 4.4117619,
            "yield": 80,
            "color": 2.0304569,
            "add_after_boil": false,
            "origin": "Australia",
            "supplier": "Barrett Burston",
            "notes": "Good pale 2-row base spring malting grade barley. Well-modified and kilned malt is required.",
            "coarse_fine_diff": 1.5,
            "moisture": 4.5,
            "diastatic_power": 230,
            "protein": 0,
            "max_in_batch": 100,
            "recommend_mash": true,
            "ibu_gal_per_lb": 0,
            "display_amount": "9 lbs 11.6 oz",
            "inventory": "8 lbs 4.3 oz",
            "potential": 1.0368,
            "display_color": "2.0 SRM",
            "extract_substitute": "Pale Liquid Extract",
            "id": "9fc07775-4441-412d-878c-52917e78c589",
            "complete": false
          },
          {
            "name": "Wheat Malt (Barrett Burston)",
            "version": 1,
            "type": "Grain",
            "amount": 0.235294,
            "yield": 81.1,
            "color": 1.2182741,
            "add_after_boil": false,
            "origin": "Australia",
            "supplier": "Barrett Burston",
            "notes": "Wheat base malt suitable for all wheat styles.",
            "coarse_fine_diff": 1.5,
            "moisture": 5,
            "diastatic_power": 95,
            "protein": 0,
            "max_in_batch": 75,
            "recommend_mash": true,
            "ibu_gal_per_lb": 0,
            "display_amount": "8.3 oz",
            "inventory": "7.1 oz",
            "potential": 1.037306,
            "display_color": "1.2 SRM",
            "extract_substitute": "Pale Liquid Extract",
            "id": "335cc51b-4c54-4b21-9c47-2019dd0e5d1d",
            "complete": false
          },
          {
            "name": "Crystal Dark Bairds",
            "version": 1,
            "type": "Grain",
            "amount": 0.0470588,
            "yield": 74.4,
            "color": 121.8274112,
            "add_after_boil": false,
            "origin": "Australia",
            "supplier": "Bairds",
            "notes": "Medium-dark crystal malt. Used for color and flavor. Use 5% to 10% for improved colour aroma. Subtle crystal sweetness.",
            "coarse_fine_diff": 1.5,
            "moisture": 5.2,
            "diastatic_power": 0,
            "protein": 0,
            "max_in_batch": 10,
            "recommend_mash": false,
            "ibu_gal_per_lb": 0,
            "display_amount": "1.7 oz",
            "inventory": "1.4 oz",
            "potential": 1.034224,
            "display_color": "121.8 SRM",
            "extract_substitute": "",
            "id": "c390ed11-2c92-4ea6-95fa-5f7ae9d23edf",
            "complete": false
          },
          {
            "name": "Gypsum (Calcium Sulfate)",
            "version": 1,
            "type": "Water Agent",
            "use": "Mash",
            "amount": 0.004,
            "time": 60,
            "amount_is_weight": true,
            "use_for": "Water Agent",
            "notes": "Reduces PH of water for mashing and sparging. Alters water profile -- used to harden soft water. Use the BeerSmith Water Profile tool to determine amount to add.",
            "display_amount": "4.00 g",
            "inventory": "192.00 g",
            "display_time": "60.0 mins",
            "batch_size": "5.00 gal",
            "id": "4eac4782-3f3c-48d0-aa28-b2b576345771",
            "complete": false
          },
          {
            "name": "Calcium Chloride",
            "version": 1,
            "type": "Water Agent",
            "use": "Mash",
            "amount": 0.002,
            "time": 60,
            "amount_is_weight": true,
            "use_for": "Water Agent",
            "notes": "Alters water profile and pH of mash. Use the BeerSmith Water Profile tool to determine amount to add.",
            "display_amount": "2.00 g",
            "inventory": "194.50 g",
            "display_time": "60.0 mins",
            "batch_size": "5.00 gal",
            "id": "b4537456-d4d7-42df-8cdf-84db4dd1ad04",
            "complete": false
          },
          {
            "name": "Epsom Salt (MgSO4)",
            "version": 1,
            "type": "Water Agent",
            "use": "Mash",
            "amount": 0.002,
            "time": 60,
            "amount_is_weight": true,
            "use_for": "Water Agent",
            "notes": "Water agent used to modify water profile. Use the BeerSmith Water Profile tool to determine amount to add.",
            "display_amount": "2.00 g",
            "inventory": "196.00 g",
            "display_time": "60.0 mins",
            "batch_size": "5.00 gal",
            "id": "06d53d84-5974-4e09-bbb5-4cec0997e3ae",
            "complete": false
          }
        ],
        "complete": false,
        "type": "ADD_INGREDIENTS"
      },
      {
        "id": "06899bc9-e5f0-4a8d-8e49-7fe53ffdbd2d",
        "title": "Mash In Heating",
        "content": "Heat Mash to 95.0 F",
        "objects": [
          {
            "name": "Mash In",
            "version": 1,
            "type": "Infusion",
            "infuse_amount": 18.7764211,
            "step_time": 5,
            "step_temp": 35,
            "ramp_time": 2,
            "end_temp": 35,
            "description": "Add 23.04 qt of water at 98.0 F",
            "water_grain_ratio": "1.917 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "98.0 F",
            "display_step_temp": "95.0 F",
            "display_infuse_amt": "23.04 qt",
            "id": "05b45621-a062-47eb-8604-b9d9b6deb708",
            "complete": false
          }
        ],
        "type": "HEATING"
      },
      {
        "id": "33b0bcc7-7355-4940-8496-36d751696231",
        "title": "Mash In Rest",
        "content": "Holding Mash at 95.0 F for 5 hour ",
        "objects": [
          {
            "name": "Mash In",
            "version": 1,
            "type": "Infusion",
            "infuse_amount": 18.7764211,
            "step_time": 5,
            "step_temp": 35,
            "ramp_time": 2,
            "end_temp": 35,
            "description": "Add 23.04 qt of water at 98.0 F",
            "water_grain_ratio": "1.917 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "98.0 F",
            "display_step_temp": "95.0 F",
            "display_infuse_amt": "23.04 qt",
            "id": "05b45621-a062-47eb-8604-b9d9b6deb708",
            "complete": false
          }
        ],
        "type": "RESTING"
      },
      {
        "id": "a1d483b0-6f37-4913-91db-70885be26866",
        "title": "Protien Rest Heating",
        "content": "Heat Mash to 125.6 F",
        "objects": [
          {
            "name": "Protien Rest",
            "version": 1,
            "type": "Temperature",
            "infuse_amount": 0,
            "step_time": 15,
            "step_temp": 52,
            "ramp_time": 10,
            "end_temp": 52,
            "description": "Heat to 125.6 F over 10 min",
            "water_grain_ratio": "2.227 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "170.0 F",
            "display_step_temp": "125.6 F",
            "display_infuse_amt": "0.00 qt",
            "id": "6d98d3bc-6ec3-4b8c-b651-690a3bcfc4a3",
            "complete": false
          }
        ],
        "type": "HEATING"
      },
      {
        "id": "c311f0a8-9110-4c25-9707-8403bd9da304",
        "title": "Protien Rest Rest",
        "content": "Holding Mash at 125.6 F for 15 hour ",
        "objects": [
          {
            "name": "Protien Rest",
            "version": 1,
            "type": "Temperature",
            "infuse_amount": 0,
            "step_time": 15,
            "step_temp": 52,
            "ramp_time": 10,
            "end_temp": 52,
            "description": "Heat to 125.6 F over 10 min",
            "water_grain_ratio": "2.227 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "170.0 F",
            "display_step_temp": "125.6 F",
            "display_infuse_amt": "0.00 qt",
            "id": "6d98d3bc-6ec3-4b8c-b651-690a3bcfc4a3",
            "complete": false
          }
        ],
        "type": "RESTING"
      },
      {
        "id": "c5596760-895f-4314-910d-4c258d6a0724",
        "title": "Sacch Rest Heating",
        "content": "Heat Mash to 145.4 F",
        "objects": [
          {
            "name": "Sacch Rest",
            "version": 1,
            "type": "Temperature",
            "infuse_amount": 0,
            "step_time": 60,
            "step_temp": 63,
            "ramp_time": 10,
            "end_temp": 63,
            "description": "Heat to 145.4 F over 10 min",
            "water_grain_ratio": "2.227 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "170.0 F",
            "display_step_temp": "145.4 F",
            "display_infuse_amt": "0.00 qt",
            "id": "1a3904ea-8cb9-4b2c-a551-89b071afa393",
            "complete": false
          }
        ],
        "type": "HEATING"
      },
      {
        "id": "3a864c2f-1b47-4a99-99d3-19baf080d281",
        "title": "Sacch Rest Rest",
        "content": "Holding Mash at 145.4 F for 1 hour ",
        "objects": [
          {
            "name": "Sacch Rest",
            "version": 1,
            "type": "Temperature",
            "infuse_amount": 0,
            "step_time": 60,
            "step_temp": 63,
            "ramp_time": 10,
            "end_temp": 63,
            "description": "Heat to 145.4 F over 10 min",
            "water_grain_ratio": "2.227 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "170.0 F",
            "display_step_temp": "145.4 F",
            "display_infuse_amt": "0.00 qt",
            "id": "1a3904ea-8cb9-4b2c-a551-89b071afa393",
            "complete": false
          }
        ],
        "type": "RESTING"
      },
      {
        "id": "e3a80faf-bd75-43a9-acce-dbca702d01df",
        "title": "Mash Out Heating",
        "content": "Heat Mash to 172.4 F",
        "objects": [
          {
            "name": "Mash Out",
            "version": 1,
            "type": "Temperature",
            "infuse_amount": 0,
            "step_time": 10,
            "step_temp": 78,
            "ramp_time": 10,
            "end_temp": 78,
            "description": "Heat to 172.4 F over 10 min",
            "water_grain_ratio": "2.227 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "170.0 F",
            "display_step_temp": "172.4 F",
            "display_infuse_amt": "0.00 qt",
            "id": "2d1e003c-59cf-4c7f-a31e-ebee8fc6b77d",
            "complete": false
          }
        ],
        "type": "HEATING"
      },
      {
        "id": "4b7b325c-3a94-415f-a76a-20690048f493",
        "title": "Mash Out Rest",
        "content": "Holding Mash at 172.4 F for 10 hour ",
        "objects": [
          {
            "name": "Mash Out",
            "version": 1,
            "type": "Temperature",
            "infuse_amount": 0,
            "step_time": 10,
            "step_temp": 78,
            "ramp_time": 10,
            "end_temp": 78,
            "description": "Heat to 172.4 F over 10 min",
            "water_grain_ratio": "2.227 qt/lb",
            "decoction_amt": "0.00 qt",
            "infuse_temp": "170.0 F",
            "display_step_temp": "172.4 F",
            "display_infuse_amt": "0.00 qt",
            "id": "2d1e003c-59cf-4c7f-a31e-ebee8fc6b77d",
            "complete": false
          }
        ],
        "type": "RESTING"
      },
      {
        "id": "3f8452e0-a018-4abd-9d75-260499c90fb4",
        "title": "Prepare for Heating Sparge Water",
        "content": "Put valves in recirculating position:",
        "todos": [
          {
            "step": "Open HLT outlet",
            "complete": false,
            "id": "10b66f59-6430-4d77-9d98-dee9de2775a3"
          },
          {
            "step": "Open pump outlet",
            "complete": false,
            "id": "775d8e89-da58-4641-be17-2f6050c0e0fa"
          },
          {
            "step": "Close top Mash Tun inlet so water flows back to HLT",
            "complete": false,
            "id": "79e99d4b-5ee7-467a-9fd7-cde37957e1d3"
          }
        ],
        "complete": false,
        "type": "PREPARE_FOR_HTL_HEAT"
      },
      {
        "id": "bb5b2c37-c6ed-4274-b66f-d8bf463e300d",
        "title": "Heat Sparge Water",
        "content": "Heating sparge water to 172.4 F",
        "objects": [
          {
            "name": "Pilsner Mash",
            "version": 1,
            "grain_temp": 22.2,
            "tun_temp": 22,
            "sparge_temp": 78,
            "ph": 5.4,
            "tun_weight": 144,
            "tun_specific_heat": 0.3,
            "equip_adjust": true,
            "notes": "",
            "display_grain_temp": "72.0 F",
            "display_tun_temp": "71.6 F",
            "display_sparge_temp": "172.4 F",
            "display_tun_weight": "9 lbs"
          }
        ],
        "setpoint": 78,
        "complete": false,
        "type": "HEATING"
      }
    ],
    "activeStep": {
      "id": "9cae17d0-0730-4df8-87f0-890f6fa85750",
      "title": "Strike Water",
      "subheader": null,
      "content": "Add the following ingredients to the Hot Liquor Tank:",
      "todos": [
        {
          "step": "9.81 gal water",
          "complete": false,
          "id": "96bcc0a1-79a2-4f34-8186-1cbae1ade046"
        },
        {
          "step": "4.00 g Gypsum (Calcium Sulfate)",
          "complete": false,
          "id": "d9401432-752b-46bf-8950-114c551be65c"
        },
        {
          "step": "2.00 g Calcium Chloride",
          "complete": false,
          "id": "2c4dc258-16cf-4499-8c82-ae974290c06e"
        },
        {
          "step": "2.00 g Epsom Salt (MgSO4)",
          "complete": false,
          "id": "a819a090-0a59-4bc4-ad07-7928cc822635"
        }
      ],
      "objects": [
        {
          "name": "Gypsum (Calcium Sulfate)",
          "version": 1,
          "type": "Water Agent",
          "use": "Mash",
          "amount": 0.004,
          "time": 60,
          "amount_is_weight": true,
          "use_for": "Water Agent",
          "notes": "Reduces PH of water for mashing and sparging. Alters water profile -- used to harden soft water. Use the BeerSmith Water Profile tool to determine amount to add.",
          "display_amount": "4.00 g",
          "inventory": "192.00 g",
          "display_time": "60.0 mins",
          "batch_size": "5.00 gal",
          "id": "4eac4782-3f3c-48d0-aa28-b2b576345771",
          "complete": false
        },
        {
          "name": "Calcium Chloride",
          "version": 1,
          "type": "Water Agent",
          "use": "Mash",
          "amount": 0.002,
          "time": 60,
          "amount_is_weight": true,
          "use_for": "Water Agent",
          "notes": "Alters water profile and pH of mash. Use the BeerSmith Water Profile tool to determine amount to add.",
          "display_amount": "2.00 g",
          "inventory": "194.50 g",
          "display_time": "60.0 mins",
          "batch_size": "5.00 gal",
          "id": "b4537456-d4d7-42df-8cdf-84db4dd1ad04",
          "complete": false
        },
        {
          "name": "Epsom Salt (MgSO4)",
          "version": 1,
          "type": "Water Agent",
          "use": "Mash",
          "amount": 0.002,
          "time": 60,
          "amount_is_weight": true,
          "use_for": "Water Agent",
          "notes": "Water agent used to modify water profile. Use the BeerSmith Water Profile tool to determine amount to add.",
          "display_amount": "2.00 g",
          "inventory": "196.00 g",
          "display_time": "60.0 mins",
          "batch_size": "5.00 gal",
          "id": "06d53d84-5974-4e09-bbb5-4cec0997e3ae",
          "complete": false
        }
      ],
      "complete": false,
      "type": "PREPARE_STRIKE_WATER"
    }
  }
}